- name: install cart
  ansible.builtin.import_role:
    name: common
    tasks_from: docker

- name: start a container
  community.docker.docker_container:
    name: shipping
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/shipping
    state: started
    restart: true
    ports:
      - "8080:8080"
    env:
      CART_ENDPOINT: "cart-dev.sandeepkumar0088.online:8080"
      DB_HOST: mysql-dev.sandeepkumar0088.online

#- name: start a container
#  loop:
#    - app-user
#    - schema
#    - master-data
#  community.docker.docker_container:
#    name: shipping-app-user
#    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
#    state: started
#    env:
#      DB_TYPE: "mysql"
#      APP_GIT_URL: "https://github:com/roboshop-devops-project-v3/shipping"
#      DB_HOST: mysql-dev.sandeepkumar0088.online
#      DB_USER: root
#      DB_PASS: RoboShop@1
#      SCHEMA_FILE: db/app-user.sql

- name: start a container
  community.docker.docker_container:
    name: shipping-app-user
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
    state: started
    env:
      DB_TYPE: "mysql"
      APP_GIT_URL: "https://github:com/roboshop-devops-project-v3/shipping"
      DB_HOST: mysql-dev.sandeepkumar0088.online
      DB_USER: root
      DB_PASS: RoboShop@1
      SCHEMA_FILE: db/app-user.sql


- name: start a container
  community.docker.docker_container:
    name: shipping-schema
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
    state: started
    env:
      DB_TYPE: "mysql"
      APP_GIT_URL: "https://github:com/roboshop-devops-project-v3/shipping"
      DB_HOST: mysql-dev.sandeepkumar0088.online
      DB_USER: root
      DB_PASS: RoboShop@1
      SCHEMA_FILE: db/schema.sql

- name: start a container
  community.docker.docker_container:
    name: shipping-master-data
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
    state: started
    env:
      DB_TYPE: "mysql"
      APP_GIT_URL: "https://github:com/roboshop-devops-project-v3/shipping"
      DB_HOST: mysql-dev.sandeepkumar0088.online
      DB_USER: root
      DB_PASS: RoboShop@1
      SCHEMA_FILE: db/master-data.sql

